// const getUser = () => ({
//   studId: 201103045,
//   admin: false,
//   firstName: 'ibrahim',
//   lastName: 'isa',
//   phoneNumber: 8160326119,
//   male: true,
//   dob: new Date(2004, 5, 26),
//   department: 'software engineering',
//   hostel: 'lakeside',
//   level: 3,
//   room: 'a1',
//   dormAdvisor: 'ale musa',
//   profilePicture: null,
//   email: 'jajere@miki.bo',
//   username: 'mikibo',
//   password: 'pword',
// });

// const getStudents = () => [
//   {
//     studId: 201103045,
//     admin: false,
//     firstName: 'ibrahim',
//     lastName: 'isa',
//     phoneNumber: 8160326119,
//     male: true,
//     dob: new Date(2004, 5, 26),
//     department: 'software engineering',
//     hostel: 'lakeside',
//     level: 3,
//     room: 'a1',
//     dormAdvisor: 'ale musa',
//     profilePicture: null,
//     email: 'jajere@miki.bo',
//     username: 'mikibo',
//     password: 'pword',
//   },
//   {
//     studId: 201203044,
//     admin: false,
//     firstName: 'ibasdfasdim',
//     lastName: 'isasdfaera',
//     phoneNumber: 816033245119,
//     male: true,
//     dob: new Date(2004, 5, 26),
//     department: 'wet42e45 engineering',
//     hostel: 'lakeasgsfgd',
//     level: 3,
//     room: 'a1',
//     dormAdvisor: 'ale musa',
//     profilePicture: null,
//     email: 'jajere@miki.bo',
//     username: 'mikibo',
//     password: 'pword',
//   },
//   {
//     studId: 20154603045,
//     admin: false,
//     firstName: 'ibasytrye',
//     lastName: 'issflkasda',
//     phoneNumber: 81432560326119,
//     male: true,
//     dob: new Date(2004, 5, 26),
//     department: 'softwaslfjjl ineering',
//     hostel: 'lakeside',
//     level: 3,
//     room: 'a1',
//     dormAdvisor: 'ale musa',
//     profilePicture: null,
//     email: 'jajere@miki.bo',
//     username: 'mikibo',
//     password: 'pword',
//   },
// ];

// const getOrders = () => [
//   {
//     id: 1,
//     orderedBy: 201103045,
//     status: 'completed',
//     date: '2023-05-01',
//     shirts: 12,
//     trousers: 23,
//     underwears: 10,
//     staff: 'babagana',
//     instructions: 'please dont blah bluh',
//   },
//   {
//     id: 2,
//     orderedBy: 201103045,
//     status: 'pending',
//     date: '2023-05-02',
//     shirts: 4,
//     trousers: 3,
//     underwears: 0,
//     staff: 'usman',
//     instructions: 'sdlfjaldk please dont blah bluh',
//   },
//   {
//     id: 3,
//     orderedBy: 201103045,
//     status: 'canceled',
//     date: '2023-05-03',
//     shirts: 12,
//     trousers: 23,
//     underwears: 10,
//     staff: 'babagana',
//     instructions: 'please dont blah bluh',
//   },
//   {
//     id: 4,
//     orderedBy: 201103045,
//     status: 'completed',
//     date: '2023-05-04',
//     shirts: 4,
//     trousers: 3,
//     underwears: 0,
//     staff: 'usman',
//     instructions: 'sdlfjaldk please dont blah bluh',
//   },
//   {
//     id: 5,
//     orderedBy: 201103045,
//     status: 'pending',
//     date: '2023-05-05',
//     shirts: 12,
//     trousers: 23,
//     underwears: 10,
//     staff: 'babagana',
//     instructions: 'please dont blah bluh',
//   },
//   {
//     id: 6,
//     orderedBy: 201103045,
//     status: 'completed',
//     date: '2023-05-06',
//     shirts: 4,
//     trousers: 3,
//     underwears: 0,
//     staff: 'usman',
//     instructions: 'sdlfjaldk please dont blah bluh',
//   },
//   {
//     id: 7,
//     orderedBy: 201103045,
//     status: 'canceled',
//     date: '2023-05-07',
//     shirts: 12,
//     trousers: 23,
//     underwears: 10,
//     staff: 'babagana',
//     instructions: 'please dont blah bluh',
//   },
//   {
//     id: 8,
//     orderedBy: 201103045,
//     status: 'completed',
//     date: '2023-05-08',
//     shirts: 4,
//     trousers: 3,
//     underwears: 0,
//     staff: 'usman',
//     instructions: 'sdlfjaldk please dont blah bluh',
//   },
//   {
//     id: 9,
//     orderedBy: 201103045,
//     status: 'pending',
//     date: '2023-05-09',
//     shirts: 12,
//     trousers: 23,
//     underwears: 10,
//     staff: 'babagana',
//     instructions: 'please dont blah bluh',
//   },
//   {
//     id: 10,
//     orderedBy: 201212030,
//     status: 'canceled',
//     date: '2023-05-10',
//     shirts: 4,
//     trousers: 3,
//     underwears: 0,
//     staff: 'usman',
//     instructions: 'sdlfjaldk please dont blah bluh',
//   },
// ];

// function getFeedbacks() {
//   return [
//     {
//       by: 201103045,
//       type: 'suggestion',
//       title: 'blah blu blah',
//       description:
//         'this is a fake descrip placeholder for actual text. hahaha im still writing, you know, just to make the text even longer.',
//     },
//     {
//       by: 20120458,
//       type: 'problem',
//       title: 'blah blu blah',
//       description:
//         'this is a fake description, it conveys  no information and its meaningless. it is just here as a placeholder for actual text. hahaha im still writing, you know, just to make the text even longer.',
//     },
//   ];
// }

// export { getOrders, getUser, getStudents, getFeedbacks };
